spring.application.name=myfirstwebapp
#server.port = 8081

# JSP View Resolver
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

# Debugging Log Levels
logging.level.org.springframework=info

# H2 In-Memory Database Configuration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Enable JPA Schema and SQL Auto-Seeding
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
